apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paymentservice
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AdarshJain-dev/11-Microservice-CD.git
    targetRevision: main
    path: paymentservice

  destination:
    server: https://kubernetes.default.svc
    namespace: webapps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
